# Generated by Django 4.0.5 on 2022-06-10 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('correoCliente', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Correo Electronico')),
                ('nombreCliente', models.CharField(max_length=50, verbose_name='Nombre Cliente')),
                ('nacionalidadCliente', models.CharField(max_length=50, verbose_name='Nombre Cliente')),
                ('sexoCliente', models.CharField(max_length=6, verbose_name='Sexo Cliente')),
                ('fechaCliente', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('telefonoCliente', models.IntegerField(max_length=9, verbose_name='Telefono Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de Producto')),
                ('nombreProducto', models.CharField(max_length=50, verbose_name='Nombre Producto')),
                ('descripcionProducto', models.CharField(max_length=10, verbose_name='Descripcion Producto')),
                ('precioProducto', models.CharField(max_length=10, verbose_name='Precio')),
            ],
        ),
    ]
