# Generated by Django 4.0.5 on 2022-06-12 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='nacionalidadCliente',
            field=models.CharField(max_length=50, verbose_name='Nacionalidad Cliente'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefonoCliente',
            field=models.IntegerField(verbose_name='Telefono Cliente'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcionProducto',
            field=models.CharField(max_length=100, verbose_name='Descripcion Producto'),
        ),
    ]
