# Generated by Django 4.0.5 on 2022-06-12 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_cliente_nacionalidadcliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='descripcionProducto',
            field=models.CharField(max_length=1000, verbose_name='Descripcion Producto'),
        ),
    ]
