# Generated by Django 4.0.5 on 2022-06-13 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_producto_nombreproducto'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='contraseñaCliente',
            field=models.CharField(default='*********', max_length=200),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombreCliente',
            field=models.CharField(max_length=100, verbose_name='Nombre Cliente'),
        ),
    ]
