# Generated by Django 4.0.5 on 2022-06-13 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_cliente_contraseñacliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='nombreCliente',
            field=models.CharField(max_length=200, verbose_name='Nombre Cliente'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='sexoCliente',
            field=models.CharField(max_length=10, verbose_name='Sexo Cliente'),
        ),
    ]
